---
- hosts: dockerhost #Doar IP-urile aflate in grupul dockerhost vor fi afectate de acest playbook

  tasks:
    - name: stop existing container
      command: docker stop regapp-server #Opreste containerul regapp-server in cazul in  care avem unul
      ignore_errors: yes  #Daca nu avem creat un container regapp-server atunci ignora erorile

    - name: remove existing container
      command: docker rm regapp-server #Sterge containerul regapp-server in cazul in care avem unul
      ignore_errors: yes #Daca nu avem creat un container regapp-server atunci ignora erorile

    - name: remove image
      command: docker rmi mateutcristian/regapp:latest #Sterge imaginea mateutcristian/regapp:latest in cazul in care avem una
      ignore_errors: yes #Daca nu avem creata o imagine mateutcristian/regapp:latest ignora erorile

    - name: create container
      command: docker run -d --name regapp-server -p 8082:8080 mateutcristian/regapp:latest #Creaza un container numit regapp-server pe portul 8082 folosind imaginea indicata
